### ISSUE TITLE
Maintainable open source pre-commit action?

### ISSUE THREAD

**Issue by mikedlr** [cloudposse/github-action-pre-commit#11]
Currently there are multiple forks of the open source pre-commit action. In order for there to be one, well maintained version there would have to be both activity and people involved, which probably means a project. 

Is cloudposse willing to host? Would you accept other people having admin rights over the repo so that there are muptiple maintainers

Other active forks include

https://github.com/wangsha/pre-commit-github-action
https://github.com/avri-schneider/action

Might be worth getting in touch with devs that have done other forks - @wangsha, @avri-schneider @asottile etc. and seeing if any would like developer access to such a shared and maintained fork. 

P.S. apologies for not asking on slack if that was what is expected, however your slack is blocking my email domains.

**Comment by osterman** [comment]
Hello @mikedlr - sorry, we didn't see your message (hence why we suggest pinging us in slack). We do maintain this action, and use it in our own projects. We're open to including other contributors with merge permissions. Get in touch with me on Slack, if this is still something you would like to pursue. 

[![Badge](https://slack.cloudposse.com/for-the-badge.svg)](https://slack.cloudposse.com)
